import type { Lang } from "../store/universe";

/** Bilingual UI strings. Translate for meaning, not lexically. */
const S = {
  appName: { en: "Neural Cosmos", es: "Neural Cosmos" },
  navigate: { en: "Navigate", es: "Navegar" },
  move: { en: "Move", es: "Mover" },
  weave: { en: "Weave", es: "Tejer" },
  add: { en: "New body", es: "Cuerpo nuevo" },
  legend: { en: "Legend", es: "Leyenda" },
  recenter: { en: "Recenter", es: "Recentrar" },
  inspector: { en: "Inspector", es: "Inspector" },
  loading: { en: "Forming the cosmos…", es: "Formando el cosmos…" },
  retry: { en: "Retry", es: "Reintentar" },
  errorTitle: { en: "The cosmos didn't load", es: "El cosmos no cargó" },
  close: { en: "Close", es: "Cerrar" },
  stage: { en: "Stage", es: "Etapa" },
  kind: { en: "Kind", es: "Tipo" },
  archetype: { en: "Archetype", es: "Arquetipo" },
  energy: { en: "Energy", es: "Energía" },
  color: { en: "Color", es: "Color" },
  advance: { en: "Advance", es: "Avanzar" },
  retreat: { en: "Retreat", es: "Retroceder" },
  enter: { en: "Enter cosmos", es: "Entrar al cosmos" },
  blackhole: { en: "Send to black hole", es: "Al agujero negro" },
  rebirth: { en: "Rebirth", es: "Renacer" },
  docs: { en: "Documents", es: "Documentos" },
  decisions: { en: "Decisions", es: "Decisiones" },
  history: { en: "History", es: "Historial" },
  details: { en: "Details", es: "Detalles" },
  addDoc: { en: "Add document", es: "Añadir documento" },
  addDecision: { en: "Add decision", es: "Añadir decisión" },
  title: { en: "Title", es: "Título" },
  body: { en: "Body", es: "Contenido" },
  rationale: { en: "Rationale", es: "Razonamiento" },
  save: { en: "Save", es: "Guardar" },
  name: { en: "Name", es: "Nombre" },
  create: { en: "Create", es: "Crear" },
  weaveHint: {
    en: "Tap two bodies to thread them",
    es: "Toca dos cuerpos para tejerlos",
  },
  moveHint: { en: "Drag a body to reposition", es: "Arrastra un cuerpo para moverlo" },
  navHint: {
    en: "Tap to inspect · hold to enter",
    es: "Toca para inspeccionar · mantén para entrar",
  },
  threadMeaning: { en: "Thread meaning", es: "Significado del hilo" },
  lifecycle: { en: "Life-cycle", es: "Ciclo de vida" },
  empty: { en: "Nothing here yet.", es: "Aún no hay nada aquí." },
  noChildCosmosLabel: {
    en: "no inner cosmos yet — creating…",
    es: "sin cosmos interno aún — creando…",
  },
  atlasHint: {
    en: "Atlas — intelligence force. Regions ready for analysis.",
    es: "Atlas — fuerza de inteligencia. Regiones listas para análisis.",
  },
  atlasConsole: { en: "Atlas console", es: "Consola Atlas" },
  openAtlas: { en: "Open Atlas console", es: "Abrir consola Atlas" },
  generate: { en: "Generate analysis", es: "Generar análisis" },
  generating: { en: "Studying…", es: "Estudiando…" },
  noAnalyses: {
    en: "No analyses yet. Generate to populate the regions.",
    es: "Sin análisis aún. Genera para poblar las regiones.",
  },
  acted: { en: "Acted", es: "Actuado" },
  dismiss: { en: "Dismiss", es: "Descartar" },
  reopen: { en: "Reopen", es: "Reabrir" },
  generatedBy: { en: "via", es: "vía" },
  scaffoldNote: {
    en: "Heuristic stub — a model plugs in here later.",
    es: "Andamiaje heurístico — aquí se enchufa un modelo después.",
  },
  subject: { en: "Subject", es: "Sujeto" },
  information: { en: "Information", es: "Información" },
  connections: { en: "Connections", es: "Conexiones" },
  descriptionLabel: { en: "Description", es: "Descripción" },
  functionLabel: { en: "Function", es: "Función" },
  tags: { en: "Tags", es: "Etiquetas" },
  status: { en: "Status", es: "Estado" },
  priority: { en: "Priority", es: "Prioridad" },
  potential: { en: "Potential", es: "Potencial" },
  risk: { en: "Risk", es: "Riesgo" },
  createdBy: { en: "Created by", es: "Creado por" },
  changeImage: { en: "Change image", es: "Cambiar imagen" },
  uploadImage: { en: "Upload image", es: "Subir imagen" },
  removeImage: { en: "Remove image", es: "Quitar imagen" },
  imageUrl: { en: "Image URL", es: "URL de imagen" },
  symbol: { en: "Symbol", es: "Símbolo" },
  animal: { en: "Animal", es: "Animal" },
  role: { en: "Role", es: "Rol" },
  statesLegend: { en: "Status legend", es: "Leyenda de estados" },
  connectionTypes: { en: "Connection types", es: "Tipos de conexión" },
  addTag: { en: "Add tag…", es: "Añadir etiqueta…" },
  noConnections: { en: "No connections yet.", es: "Sin conexiones aún." },
  // sidebar / chrome
  navGalaxy: { en: "Galaxy", es: "Galaxy" },
  navFlows: { en: "Flows", es: "Flujos" },
  navNodes: { en: "Nodes", es: "Nodos" },
  navDocuments: { en: "Documents", es: "Documentos" },
  navIntelligence: { en: "Intelligence", es: "Inteligencia" },
  navHistory: { en: "History", es: "Historial" },
  navSettings: { en: "Settings", es: "Ajustes" },
  searchNode: { en: "Search node…", es: "Buscar nodo…" },
  subtitle: { en: "Enterprise neural map", es: "Mapa neuronal empresarial" },
  quickActions: { en: "Quick actions", es: "Accesos rápidos" },
  newNode: { en: "New node", es: "Nuevo nodo" },
  newConnection: { en: "New connection", es: "Nueva conexión" },
  importJson: { en: "Import JSON", es: "Importar JSON" },
  exportJson: { en: "Export JSON", es: "Exportar JSON" },
  aiSuggestions: { en: "AI suggestions", es: "Sugerencias IA" },
  mainNodes: { en: "Main nodes", es: "Nodos principales" },
  quality: { en: "Quality", es: "Calidad" },
  high: { en: "High", es: "Alta" },
  performance: { en: "Performance", es: "Rendimiento" },
  language: { en: "Language", es: "Idioma" },
  allDocuments: { en: "All documents", es: "Todos los documentos" },
  allHistory: { en: "All history", es: "Todo el historial" },
  bloom: { en: "Bloom glow", es: "Resplandor (bloom)" },
  viewGalaxy: { en: "Galaxy", es: "Galaxia" },
  viewOracle: { en: "Oracle", es: "Oráculo" },
  view3d: { en: "3D view", es: "Vista 3D" },
  galaxyTitle: { en: "Neural Galaxy", es: "Neural Galaxy" },
} as const;

export type StringKey = keyof typeof S;
export const t = (key: StringKey, lang: Lang): string => S[key][lang];
