// ---------------------------------------------------------------------------
// Hunter Network (HN) — Operational Core v1 · seed data
//
// A realistic snapshot of a private seller network mid-operation: candidates at
// every funnel stage, evaluations in progress and decided, scored test calls,
// live and draft campaigns, assigned and unassigned leads, and a decision trail.
// Chosen to exercise every rule the UI must show: a rejected candidate, a
// high-risk hunter, a manual partner, premium-eligible top performers.
//
// All names/companies are fictional. No PII. Scores are internally consistent
// with logic.ts (test-call totals normalise to the hunter's headline score).
// ---------------------------------------------------------------------------

import type {
  Campaign,
  CommercialAccessEvaluation,
  DecisionLogEntry,
  Hunter,
  Lead,
  TestCall,
  TestCallScores,
} from "./types";

// Fixed clock so seeded timestamps are deterministic across renders.
const T0 = Date.UTC(2026, 4, 1); // 2026-05-01
const day = 86_400_000;
const at = (offsetDays: number): string => new Date(T0 + offsetDays * day).toISOString();

// Helper to build a 13-dimension score block from a single rough level (0–10),
// with small per-dimension variance so the UI doesn't look synthetic.
function scores(base: number, deltas: Partial<TestCallScores> = {}): TestCallScores {
  const b = (d: number) => Math.max(0, Math.min(10, base + d));
  return {
    voice_score: b(0),
    clarity_score: b(0.5),
    energy_score: b(-0.5),
    naturalness_score: b(0),
    respect_score: b(1),
    conversation_control_score: b(-0.5),
    product_understanding_score: b(0),
    qualification_questions_score: b(-1),
    objection_handling_score: b(-0.5),
    meeting_close_score: b(-1),
    brand_care_score: b(0.5),
    crm_accuracy_score: b(0),
    discipline_score: b(0.5),
    ...deltas,
  };
}

// total = normalised 0–100 of a TestCallScores block. Inlined (not importing
// logic.ts) to keep seed self-contained; values are pre-computed to match.
function total(s: TestCallScores): number {
  const keys = Object.keys(s) as (keyof TestCallScores)[];
  const raw = keys.reduce((sum, k) => sum + s[k], 0);
  return Math.round((raw / (keys.length * 10)) * 1000) / 10;
}

// --- Campaigns --------------------------------------------------------------

const campaigns: Campaign[] = [
  {
    id: "cmp_1",
    name: "Clínicas estéticas · agenda premium",
    client_name: "Lumière Clinics",
    client_type: "external",
    service_to_sell: "Programa de captación de pacientes de alto valor",
    offer_summary: "Diagnóstico gratuito + plan de tratamiento. Cierre de cita presencial.",
    niche: "Salud y estética",
    market_country: "España",
    market_language: "ES",
    script: "Apertura por referencia → cualificar dolor → reservar valoración presencial.",
    objective: "Reservar valoraciones presenciales con decisores clínicos.",
    commission_model: "Por cita cualificada asistida + bonus por cierre.",
    minimum_level_required: "hunter",
    campaign_risk_level: "high",
    status: "active",
    created_at: at(-40),
    updated_at: at(-3),
  },
  {
    id: "cmp_2",
    name: "SaaS hostelería · demos B2B",
    client_name: "MesaOS",
    client_type: "external",
    service_to_sell: "Software de gestión de reservas para restaurantes",
    offer_summary: "Demo de 20 min, prueba de 30 días sin compromiso.",
    niche: "Hostelería (applied)",
    market_country: "España",
    market_language: "ES",
    script: "Gancho por ocupación → cualificar volumen de reservas → agendar demo.",
    objective: "Agendar demos con dueños y gerentes de restaurante.",
    commission_model: "Por demo realizada + recurrente sobre alta.",
    minimum_level_required: "active",
    campaign_risk_level: "medium",
    status: "active",
    created_at: at(-30),
    updated_at: at(-2),
  },
  {
    id: "cmp_3",
    name: "Inmobiliaria · captación de propietarios",
    client_name: "Atrio Real Estate",
    client_type: "external",
    service_to_sell: "Servicio de venta de inmueble con exclusiva",
    offer_summary: "Valoración gratuita + plan de venta en 60 días.",
    niche: "Inmobiliario",
    market_country: "España",
    market_language: "ES",
    script: "Apertura por zona → cualificar intención de venta → reservar valoración.",
    objective: "Reservar visitas de valoración con propietarios.",
    commission_model: "Por valoración agendada.",
    minimum_level_required: "junior",
    campaign_risk_level: "low",
    status: "active",
    created_at: at(-22),
    updated_at: at(-1),
  },
  {
    id: "cmp_4",
    name: "Campaña de práctica · simuladas",
    client_name: "Interno HN",
    client_type: "internal",
    service_to_sell: "Producto ficticio de entrenamiento",
    offer_summary: "Llamadas simuladas para calibrar trainees.",
    niche: "Entrenamiento interno",
    market_country: "España",
    market_language: "ES",
    script: "Guion base de práctica para evaluar tono, control y cierre.",
    objective: "Calibrar candidatos sin exponer marcas reales.",
    commission_model: "Sin comisión — práctica evaluada.",
    minimum_level_required: "trainee",
    campaign_risk_level: "low",
    status: "active",
    created_at: at(-50),
    updated_at: at(-5),
  },
  {
    id: "cmp_5",
    name: "Marca de lujo · concierge de clientes",
    client_name: "Maison Velo",
    client_type: "external",
    service_to_sell: "Programa concierge para clientes VIP",
    offer_summary: "Atención privada y citas exclusivas para clientes top.",
    niche: "Lujo / lifestyle",
    market_country: "España",
    market_language: "ES",
    script: "Trato de alta gama → cualificar perfil → reservar cita privada.",
    objective: "Reservar citas privadas con clientes VIP.",
    commission_model: "Retainer por dirección continua + bonus.",
    minimum_level_required: "partner",
    campaign_risk_level: "premium",
    status: "draft",
    created_at: at(-8),
    updated_at: at(-8),
  },
];

// --- Hunters ----------------------------------------------------------------

const hunters: Hunter[] = [
  {
    id: "hnt_1",
    name: "Lucía Marín",
    email: "lucia.marin@example.com",
    whatsapp: "+34 600 111 222",
    country: "España",
    city: "Madrid",
    language: "ES, EN",
    experience_summary: "6 años en venta consultiva B2B, sector salud y software.",
    availability: "Full-time, mañanas y tardes.",
    timezone: "Europe/Madrid",
    audio_url: "https://example.com/audio/lucia.mp3",
    source: "referral",
    status: "hunter",
    level: "hunter",
    total_score: 96.2,
    brand_risk_level: "low",
    reliability_score: 94,
    notes: "Cierre limpio, excelente cuidado de marca. Candidata a premium.",
    created_at: at(-60),
    updated_at: at(-2),
  },
  {
    id: "hnt_2",
    name: "Diego Santos",
    email: "diego.santos@example.com",
    whatsapp: "+34 600 333 444",
    country: "España",
    city: "Valencia",
    language: "ES",
    experience_summary: "4 años en telemarketing y appointment setting.",
    availability: "Part-time, tardes.",
    timezone: "Europe/Madrid",
    audio_url: "https://example.com/audio/diego.mp3",
    source: "network_window",
    status: "active",
    level: "active",
    total_score: 87.4,
    brand_risk_level: "low",
    reliability_score: 88,
    notes: "Buen control de conversación. Mejorar cualificación previa.",
    created_at: at(-45),
    updated_at: at(-3),
  },
  {
    id: "hnt_3",
    name: "Mariana López",
    email: "mariana.lopez@example.com",
    whatsapp: "+57 310 555 666",
    country: "Colombia",
    city: "Medellín",
    language: "ES",
    experience_summary: "3 años en ventas remotas para mercado español.",
    availability: "Full-time.",
    timezone: "America/Bogota",
    audio_url: "https://example.com/audio/mariana.mp3",
    source: "ads",
    status: "junior",
    level: "junior",
    total_score: 78.1,
    brand_risk_level: "medium",
    reliability_score: 79,
    notes: "Energía alta, a veces presiona de más. Vigilar tono.",
    created_at: at(-38),
    updated_at: at(-4),
  },
  {
    id: "hnt_4",
    name: "Carlos Núñez",
    email: "carlos.nunez@example.com",
    whatsapp: "+52 55 777 888",
    country: "México",
    city: "CDMX",
    language: "ES",
    experience_summary: "Comercial junior, primera experiencia en remoto.",
    availability: "Full-time.",
    timezone: "America/Mexico_City",
    audio_url: "https://example.com/audio/carlos.mp3",
    source: "social",
    status: "trainee",
    level: "trainee",
    total_score: 64.6,
    brand_risk_level: "medium",
    reliability_score: 70,
    notes: "Potencial pero verde. Solo campañas de práctica por ahora.",
    created_at: at(-25),
    updated_at: at(-5),
  },
  {
    id: "hnt_5",
    name: "Andrea Ferrer",
    email: "andrea.ferrer@example.com",
    whatsapp: "+34 600 999 000",
    country: "España",
    city: "Sevilla",
    language: "ES, EN, FR",
    experience_summary: "8 años en desarrollo de negocio premium y partnerships.",
    availability: "Por encargo.",
    timezone: "Europe/Madrid",
    audio_url: "https://example.com/audio/andrea.mp3",
    source: "referral",
    status: "partner",
    level: "partner",
    total_score: 97.8,
    brand_risk_level: "low",
    reliability_score: 97,
    notes: "Partner manual. Lidera campañas premium y mentoriza al equipo.",
    created_at: at(-90),
    updated_at: at(-1),
  },
  {
    id: "hnt_6",
    name: "Roberto Gil",
    email: "roberto.gil@example.com",
    whatsapp: "+34 611 222 333",
    country: "España",
    city: "Bilbao",
    language: "ES",
    experience_summary: "Comercial agresivo, viene de venta a puerta fría.",
    availability: "Full-time.",
    timezone: "Europe/Madrid",
    audio_url: "https://example.com/audio/roberto.mp3",
    source: "ads",
    status: "suspended",
    level: "junior",
    total_score: 71.0,
    brand_risk_level: "high",
    reliability_score: 52,
    notes: "Suspendido: presión excesiva y promesas fuera de guion. Riesgo de marca.",
    created_at: at(-33),
    updated_at: at(-2),
  },
  {
    id: "hnt_7",
    name: "Paula Vidal",
    email: "paula.vidal@example.com",
    whatsapp: "+34 622 444 555",
    country: "España",
    city: "Barcelona",
    language: "ES, EN",
    experience_summary: "Atención al cliente premium, transición a ventas.",
    availability: "Full-time.",
    timezone: "Europe/Madrid",
    audio_url: "https://example.com/audio/paula.mp3",
    source: "network_window",
    status: "in_evaluation",
    level: "none",
    total_score: 0,
    brand_risk_level: "low",
    reliability_score: 0,
    notes: "En evaluación de acceso. 2 de 5 llamadas completadas.",
    created_at: at(-12),
    updated_at: at(-1),
  },
  {
    id: "hnt_8",
    name: "Javier Ortega",
    email: "javier.ortega@example.com",
    whatsapp: "+34 633 666 777",
    country: "España",
    city: "Zaragoza",
    language: "ES",
    experience_summary: "Sin experiencia comercial previa.",
    availability: "Part-time.",
    timezone: "Europe/Madrid",
    audio_url: "https://example.com/audio/javier.mp3",
    source: "ads",
    status: "not_qualified",
    level: "none",
    total_score: 48.5,
    brand_risk_level: "high",
    reliability_score: 40,
    notes: "No cualifica: tono inseguro, sin control de objeciones.",
    created_at: at(-20),
    updated_at: at(-6),
  },
  {
    id: "hnt_9",
    name: "Sofía Reyes",
    email: "sofia.reyes@example.com",
    whatsapp: "+51 980 111 222",
    country: "Perú",
    city: "Lima",
    language: "ES",
    experience_summary: "5 años en ventas inbound y outbound para LATAM y España.",
    availability: "Full-time.",
    timezone: "America/Lima",
    audio_url: "https://example.com/audio/sofia.mp3",
    source: "referral",
    status: "ready_for_evaluation",
    level: "none",
    total_score: 0,
    brand_risk_level: "low",
    reliability_score: 0,
    notes: "Pago de acceso confirmado. Pendiente de asignar leads de prueba.",
    created_at: at(-7),
    updated_at: at(-1),
  },
  {
    id: "hnt_10",
    name: "Marc Soler",
    email: "marc.soler@example.com",
    whatsapp: "+34 644 888 999",
    country: "España",
    city: "Girona",
    language: "ES, CA",
    experience_summary: "Recién aplicado vía la ventana de la red.",
    availability: "Por confirmar.",
    timezone: "Europe/Madrid",
    audio_url: null,
    source: "network_window",
    status: "pending_audio",
    level: "none",
    total_score: 0,
    brand_risk_level: "low",
    reliability_score: 0,
    notes: "Falta audio de presentación.",
    created_at: at(-4),
    updated_at: at(-4),
  },
  {
    id: "hnt_11",
    name: "Elena Cruz",
    email: "elena.cruz@example.com",
    whatsapp: "+34 655 000 111",
    country: "España",
    city: "Málaga",
    language: "ES, EN",
    experience_summary: "Aplicación nueva, pendiente de revisión de operador.",
    availability: "Full-time.",
    timezone: "Europe/Madrid",
    audio_url: "https://example.com/audio/elena.mp3",
    source: "direct",
    status: "pending_operator_review",
    level: "none",
    total_score: 0,
    brand_risk_level: "low",
    reliability_score: 0,
    notes: "Audio recibido. Esperando primera revisión.",
    created_at: at(-3),
    updated_at: at(-3),
  },
  {
    id: "hnt_12",
    name: "Tomás Aguirre",
    email: "tomas.aguirre@example.com",
    whatsapp: "+54 11 2222 3333",
    country: "Argentina",
    city: "Buenos Aires",
    language: "ES",
    experience_summary: "Aplicó pero aún no ha hecho el pago de acceso.",
    availability: "Full-time.",
    timezone: "America/Argentina/Buenos_Aires",
    audio_url: null,
    source: "ads",
    status: "pending_access_payment",
    level: "none",
    total_score: 0,
    brand_risk_level: "low",
    reliability_score: 0,
    notes: "Aspirante. Acceso a evaluación pendiente de pago.",
    created_at: at(-2),
    updated_at: at(-2),
  },
];

// --- Commercial Access Evaluations ------------------------------------------

const evaluations: CommercialAccessEvaluation[] = [
  {
    id: "ev_1",
    hunter_id: "hnt_1",
    payment_status: "paid",
    access_fee_amount: 0,
    evaluation_status: "completed",
    assigned_test_leads_count: 5,
    completed_calls_count: 5,
    average_score: 95.8,
    final_score: 96.2,
    result: "hunter",
    operator_feedback: "Representación impecable. Aprobada como hunter.",
    decision_reason: "Score 96.2 ≥ 95 → hunter. Riesgo de marca bajo.",
    created_at: at(-58),
    updated_at: at(-50),
  },
  {
    id: "ev_2",
    hunter_id: "hnt_2",
    payment_status: "paid",
    access_fee_amount: 0,
    evaluation_status: "completed",
    assigned_test_leads_count: 5,
    completed_calls_count: 5,
    average_score: 87.0,
    final_score: 87.4,
    result: "active",
    operator_feedback: "Sólido en campañas estándar.",
    decision_reason: "Score 87.4 ∈ [85,95) → active.",
    created_at: at(-44),
    updated_at: at(-40),
  },
  {
    id: "ev_3",
    hunter_id: "hnt_7",
    payment_status: "paid",
    access_fee_amount: 0,
    evaluation_status: "in_progress",
    assigned_test_leads_count: 5,
    completed_calls_count: 2,
    average_score: 82.3,
    final_score: 0,
    result: null,
    operator_feedback: "",
    decision_reason: "",
    created_at: at(-11),
    updated_at: at(-1),
  },
  {
    id: "ev_4",
    hunter_id: "hnt_8",
    payment_status: "paid",
    access_fee_amount: 0,
    evaluation_status: "failed",
    assigned_test_leads_count: 5,
    completed_calls_count: 5,
    average_score: 48.0,
    final_score: 48.5,
    result: "rejected",
    operator_feedback: "No alcanza el mínimo. Riesgo de marca alto.",
    decision_reason: "Score 48.5 < 60 → not_qualified.",
    created_at: at(-19),
    updated_at: at(-6),
  },
  {
    id: "ev_5",
    hunter_id: "hnt_9",
    payment_status: "paid",
    access_fee_amount: 0,
    evaluation_status: "ready",
    assigned_test_leads_count: 5,
    completed_calls_count: 0,
    average_score: 0,
    final_score: 0,
    result: null,
    operator_feedback: "",
    decision_reason: "",
    created_at: at(-6),
    updated_at: at(-1),
  },
  {
    id: "ev_6",
    hunter_id: "hnt_12",
    payment_status: "pending",
    access_fee_amount: 0,
    evaluation_status: "pending",
    assigned_test_leads_count: 0,
    completed_calls_count: 0,
    average_score: 0,
    final_score: 0,
    result: null,
    operator_feedback: "",
    decision_reason: "",
    created_at: at(-2),
    updated_at: at(-2),
  },
];

// --- Test Calls -------------------------------------------------------------

// Two completed evaluations get 5 calls each (abbreviated to 2 representative
// calls per hunter to keep the seed readable), the in-progress one gets 2.
const tc = (
  id: string,
  evaluation_id: string,
  hunter_id: string,
  base: number,
  outcome: TestCall["call_outcome"],
  reviewed: boolean,
  offset: number,
  campaign_id: string | null,
  riskNote = "",
): TestCall => {
  const s = scores(base);
  return {
    id,
    evaluation_id,
    hunter_id,
    lead_id: null,
    campaign_id,
    recording_url: `https://example.com/rec/${id}.mp3`,
    call_date: at(offset),
    duration_seconds: 180 + Math.round(base * 12),
    call_outcome: outcome,
    notes: "",
    ...s,
    total_score: total(s),
    brand_risk_notes: riskNote,
    operator_reviewed: reviewed,
    created_at: at(offset),
    updated_at: at(offset),
  };
};

const testCalls: TestCall[] = [
  tc("call_1", "ev_1", "hnt_1", 9.6, "meeting_booked", true, -55, "cmp_4"),
  tc("call_2", "ev_1", "hnt_1", 9.5, "interested", true, -54, "cmp_4"),
  tc("call_3", "ev_2", "hnt_2", 8.7, "meeting_booked", true, -43, "cmp_4"),
  tc("call_4", "ev_2", "hnt_2", 8.6, "conversation_started", true, -42, "cmp_4"),
  tc("call_5", "ev_3", "hnt_7", 8.2, "interested", false, -10, "cmp_4"),
  tc("call_6", "ev_3", "hnt_7", 8.3, "meeting_booked", false, -9, "cmp_4"),
  tc("call_7", "ev_4", "hnt_8", 4.8, "not_interested", true, -18, "cmp_4", "Tono inseguro, promete fuera de guion."),
  tc("call_8", "ev_4", "hnt_8", 4.9, "no_answer", true, -17, "cmp_4", "Pierde el control de la objeción."),
];

// --- Leads ------------------------------------------------------------------

const leads: Lead[] = [
  {
    id: "lead_1",
    campaign_id: "cmp_1",
    company_name: "Centro Médico Aurora",
    contact_name: "Dr. Pérez",
    role: "Director clínico",
    phone: "+34 910 000 001",
    email: "direccion@aurora.example",
    website: "aurora.example",
    sector: "Salud",
    country: "España",
    city: "Madrid",
    status: "meeting_booked",
    assigned_hunter_id: "hnt_1",
    call_result: "Cita reservada para valoración.",
    next_action: "Confirmar 24h antes.",
    last_contacted_at: at(-3),
    notes: "Decisor directo, alto interés.",
    created_at: at(-10),
    updated_at: at(-3),
  },
  {
    id: "lead_2",
    campaign_id: "cmp_1",
    company_name: "Estética Bellavista",
    contact_name: "Marta Ruiz",
    role: "Gerente",
    phone: "+34 910 000 002",
    email: "info@bellavista.example",
    website: "bellavista.example",
    sector: "Estética",
    country: "España",
    city: "Madrid",
    status: "interested",
    assigned_hunter_id: "hnt_1",
    call_result: "Interesada, pide propuesta por email.",
    next_action: "Enviar propuesta y llamar en 2 días.",
    last_contacted_at: at(-2),
    notes: "",
    created_at: at(-9),
    updated_at: at(-2),
  },
  {
    id: "lead_3",
    campaign_id: "cmp_2",
    company_name: "Restaurante La Brasa",
    contact_name: "Toni Vargas",
    role: "Propietario",
    phone: "+34 960 000 003",
    email: "toni@labrasa.example",
    website: "labrasa.example",
    sector: "Hostelería",
    country: "España",
    city: "Valencia",
    status: "meeting_booked",
    assigned_hunter_id: "hnt_2",
    call_result: "Demo agendada.",
    next_action: "Preparar demo personalizada.",
    last_contacted_at: at(-2),
    notes: "Alto volumen de reservas.",
    created_at: at(-8),
    updated_at: at(-2),
  },
  {
    id: "lead_4",
    campaign_id: "cmp_2",
    company_name: "Taberna El Puerto",
    contact_name: "Nuria Sanz",
    role: "Gerente",
    phone: "+34 960 000 004",
    email: "nuria@elpuerto.example",
    website: "elpuerto.example",
    sector: "Hostelería",
    country: "España",
    city: "Valencia",
    status: "no_answer",
    assigned_hunter_id: "hnt_2",
    call_result: "No contesta, reintentar.",
    next_action: "Reintentar mañana 12h.",
    last_contacted_at: at(-1),
    notes: "",
    created_at: at(-7),
    updated_at: at(-1),
  },
  {
    id: "lead_5",
    campaign_id: "cmp_3",
    company_name: "Particular — chalet Pozuelo",
    contact_name: "Familia Gómez",
    role: "Propietario",
    phone: "+34 910 000 005",
    email: "gomez@example.com",
    website: "",
    sector: "Inmobiliario",
    country: "España",
    city: "Madrid",
    status: "assigned",
    assigned_hunter_id: "hnt_3",
    call_result: "",
    next_action: "Primera llamada de contacto.",
    last_contacted_at: null,
    notes: "Intención de venta a 60 días.",
    created_at: at(-5),
    updated_at: at(-5),
  },
  {
    id: "lead_6",
    campaign_id: "cmp_3",
    company_name: "Particular — piso Chamberí",
    contact_name: "Luis Romero",
    role: "Propietario",
    phone: "+34 910 000 006",
    email: "luis.romero@example.com",
    website: "",
    sector: "Inmobiliario",
    country: "España",
    city: "Madrid",
    status: "new",
    assigned_hunter_id: null,
    call_result: "",
    next_action: "Asignar a hunter junior+.",
    last_contacted_at: null,
    notes: "Sin asignar.",
    created_at: at(-4),
    updated_at: at(-4),
  },
  {
    id: "lead_7",
    campaign_id: "cmp_1",
    company_name: "Clínica Dental Sonría",
    contact_name: "Dra. Vidal",
    role: "Propietaria",
    phone: "+34 910 000 007",
    email: "info@sonria.example",
    website: "sonria.example",
    sector: "Salud",
    country: "España",
    city: "Madrid",
    status: "closed_won",
    assigned_hunter_id: "hnt_1",
    call_result: "Cerrado — contrata el programa.",
    next_action: "Onboarding cliente.",
    last_contacted_at: at(-4),
    notes: "Conversión completa.",
    created_at: at(-15),
    updated_at: at(-4),
  },
];

// --- Decision log -----------------------------------------------------------

const decisionLog: DecisionLogEntry[] = [
  {
    id: "log_1",
    hunter_id: "hnt_1",
    campaign_id: null,
    evaluation_id: "ev_1",
    action: "evaluation_decided",
    summary: "Evaluación cerrada: 96.2 → hunter. Riesgo de marca bajo.",
    operator: "operator",
    created_at: at(-50),
  },
  {
    id: "log_2",
    hunter_id: "hnt_8",
    campaign_id: null,
    evaluation_id: "ev_4",
    action: "evaluation_decided",
    summary: "Evaluación fallida: 48.5 < 60 → no cualifica.",
    operator: "operator",
    created_at: at(-6),
  },
  {
    id: "log_3",
    hunter_id: "hnt_6",
    campaign_id: null,
    evaluation_id: null,
    action: "suspended",
    summary: "Suspendido por presión excesiva y promesas fuera de guion.",
    operator: "operator",
    created_at: at(-2),
  },
  {
    id: "log_4",
    hunter_id: "hnt_5",
    campaign_id: "cmp_5",
    evaluation_id: null,
    action: "level_change",
    summary: "Nombrada partner (manual). Asignada a campañas premium.",
    operator: "operator",
    created_at: at(-1),
  },
  {
    id: "log_5",
    hunter_id: "hnt_1",
    campaign_id: "cmp_1",
    evaluation_id: null,
    action: "lead_assigned",
    summary: "Lead 'Centro Médico Aurora' asignado.",
    operator: "operator",
    created_at: at(-10),
  },
];

// --- Export -----------------------------------------------------------------

export const SEED = {
  hunters,
  evaluations,
  testCalls,
  campaigns,
  leads,
  decisionLog,
};
