// =============================================================================
// seed.js — Demonstration dataset.
//
// These are SYNTHETIC, representative Spanish business archetypes. They exist
// to exercise the engine and the UI end-to-end. They are NOT verified leads and
// the citation URLs are illustrative placeholders.
//
// Why synthetic? The brief's own evidence rule is absolute: "No evidence = do
// not claim it." Attaching real names to unverified "evidence" would violate
// that rule. The honest demo path is: realistic archetypes here, real evidence
// later through the enrichment connectors (see enrichment.js + README).
//
// Signal shorthand `S` maps, in order, to the ten filters in models.FILTER_KEYS:
//   transition, economicCapacity, visibleTension, actionableLever,
//   activePain, whyNow, reachableDecisionMaker, budgetPriority,
//   strategicFit, brutalFinalFilter
// Codes: G=green  Y=yellow  R=red  X=grey
// =============================================================================

import { FILTER_KEYS } from "./models.js";

const CODE = { G: "green", Y: "yellow", R: "red", X: "grey" };

/** Expand a 10-char shorthand string into a signals object. */
function expandSignals(s) {
  const out = {};
  const chars = s.replace(/\s/g, "").split("");
  FILTER_KEYS.forEach((key, i) => {
    out[key] = { level: CODE[chars[i]] || "grey" };
  });
  return out;
}

/** Normalise a compact seed row into a full opportunity object. */
function mk(row) {
  const { S, dm, offer, ...rest } = row;
  return {
    country: "Spain",
    synthetic: true,
    signals: expandSignals(S),
    decisionMaker: dm,
    suggestedOfferKey: offer,
    ...rest,
  };
}

// Shorthand for evidence points.
const ev = (filter, type, source, note, tier, url) => ({
  filter,
  type,
  source,
  note,
  tier,
  url: url || null,
});

export const SEED = [
  // ---------------------------------------------------------------- HEALTH
  mk({
    id: "h-aurea-clinics",
    company: "Áurea Clínicas Dentales",
    sector: "health",
    subsector: "Dental / aesthetic dentistry group",
    city: "Valencia",
    region: "Comunidad Valenciana",
    website: "https://aurea-clinicas.example.es",
    instagram: "@aurea.clinicas",
    linkedin: "company/aurea-clinicas",
    googleMaps: "https://maps.example/aurea-valencia",
    phone: "+34 960 00 11 22",
    email: "direccion@aurea-clinicas.example.es",
    dm: { name: "Marta Sospedra", role: "Founder / Medical Director", linkedin: "in/marta-sospedra" },
    S: "GGGGGGGGGY",
    evidence: [
      ev("transitionSignal", "press", "Local press", "Opened a fourth clinic (Ruzafa) in Mar 2026; press release mentions a fifth planned.", 3, "https://press.example/aurea-fourth"),
      ev("whyNow", "press", "Local press", "Opening event covered this month — fresh hook for a call.", 3, "https://press.example/aurea-opening"),
      ev("activePainSignal", "review", "Google reviews", "Recurring 1–2★ reviews about phone booking and no online appointment system.", 3, "https://maps.example/aurea-reviews"),
      ev("economicCapacity", "directory", "Business directory", "4 locations, implantology + aesthetic lines = high-ticket per patient.", 2),
      ev("visibleTension", "web", "Website audit", "Site is a single 2019 one-pager, no per-clinic pages, no booking funnel.", 2, "https://aurea-clinicas.example.es"),
    ],
    tensions: ["growth_structure", "visibility_conversion", "expansion_systems"],
    thesis: "This company is likely losing qualified high-ticket patients because it has not yet solved online booking and per-location digital architecture during a four-clinic expansion.",
    summary: "A dental group is opening its fourth clinic this month while running a 2019 one-page site with phone-only booking. Reviews already complain about appointment friction. The expansion is outpacing the digital structure that should support it.",
    whyNow: "A new clinic opened this month and a fifth is announced — the structural gap is widening right now, and the opening gives a natural reason to call.",
    whyBeforeOthers: "Rare combination: clear timing trigger, named medical-director decision maker, active pain in reviews, and obvious high-ticket capacity.",
    blindSpot: "Each new clinic multiplies the booking-friction loss; they likely read it as 'more patients' not 'more leakage per location'.",
    firstLever: "Per-clinic web architecture + online booking funnel feeding a single intake.",
    offer: "web_funnel",
    callOpening: "Vi que acabáis de abrir en Ruzafa — enhorabuena. ¿Cómo estáis gestionando las citas de las cuatro clínicas desde la web?",
    objection: "Ya tenemos quien nos lleva la web.",
    objectionResponse: "Perfecto — no venimos a rehacerla por gusto. Os enseño en 15 minutos cuántas citas se pierden en el paso de teléfono a agenda; si no hay fuga, no hay proyecto.",
    reasonsNotToCall: ["Medical director may be saturated mid-opening.", "Could already have an agency on retainer."],
    invalidators: ["They already run online booking and per-clinic pages.", "Reviews about booking turn out to be stale/resolved."],
  }),

  mk({
    id: "h-vitalia-physio",
    company: "Vitalia Sports & Recovery",
    sector: "health",
    subsector: "Sports medicine / physiotherapy",
    city: "Madrid",
    region: "Madrid",
    website: "https://vitalia-recovery.example.es",
    instagram: "@vitalia.recovery",
    linkedin: "company/vitalia-recovery",
    googleMaps: "https://maps.example/vitalia-madrid",
    phone: "+34 910 22 33 44",
    email: "hola@vitalia-recovery.example.es",
    dm: { name: "Iván Cuesta", role: "Co-founder / Gerente", linkedin: "in/ivan-cuesta-physio" },
    S: "GGGGYGGGGY",
    evidence: [
      ev("transitionSignal", "jobs", "Job board", "Two open roles posted this month: clinic manager + marketing assistant.", 3, "https://jobs.example/vitalia"),
      ev("economicCapacity", "web", "Website", "Premium recovery tech (cryo, hyperbaric) — high session price, athlete clientele.", 3),
      ev("visibleTension", "instagram", "Instagram", "Strong athlete content but bio links to a Linktree, not a booking page.", 2, "https://instagram.example/vitalia"),
      ev("activePainSignal", "jobs", "Job board", "Hiring a marketing assistant signals an unowned acquisition problem.", 2),
      ev("whyNow", "instagram", "Instagram", "Just announced a second studio location for Q3.", 2),
    ],
    tensions: ["quality_perception", "visibility_conversion", "ambition_maturity"],
    thesis: "This company is likely underusing its premium positioning because it has not yet solved the gap between elite content and a conversion-ready booking path.",
    summary: "A premium sports-recovery studio with athlete-grade equipment is hiring its first marketing person and opening a second site. Its acquisition runs through Instagram into a Linktree, not a funnel. Demand exists; capture does not.",
    whyNow: "A marketing hire + a second-location announcement mean they are actively trying to solve growth — and haven't yet.",
    whyBeforeOthers: "Premium price point and a named gerente make this a clean, fundable 01 engagement with strong before/after.",
    blindSpot: "They are about to hire internally for a problem a funnel + positioning system would solve faster and cheaper.",
    firstLever: "Repositioning + a conversion landing page that replaces the Linktree.",
    offer: "reposition",
    callOpening: "Vi que estáis buscando perfil de marketing y abrís segundo centro — ¿quién os está montando el embudo de captación mientras tanto?",
    objection: "Vamos a contratar a alguien interno para eso.",
    objectionResponse: "Genial, y esa persona necesitará un sistema sobre el que trabajar. Os lo dejamos montado en 3 semanas para que entre a optimizar, no a improvisar.",
    reasonsNotToCall: ["May prefer to keep marketing fully in-house.", "Second studio could absorb all attention/budget short-term."],
    invalidators: ["The marketing hire is senior and will own strategy.", "They already have a booking funnel behind the Linktree."],
  }),

  mk({
    id: "h-derma-norte",
    company: "Derma Norte Estética Médica",
    sector: "health",
    subsector: "Aesthetic medicine clinic",
    city: "Bilbao",
    region: "País Vasco",
    website: "https://dermanorte.example.es",
    instagram: "@dermanorte",
    linkedin: "company/derma-norte",
    googleMaps: "https://maps.example/dermanorte",
    phone: "+34 944 55 66 77",
    email: "info@dermanorte.example.es",
    dm: { name: "Dra. Leire Otxoa", role: "Owner / Lead Physician", linkedin: "in/leire-otxoa" },
    S: "YGGGYYYGGY",
    evidence: [
      ev("economicCapacity", "web", "Website", "Premium aesthetic treatments, packages above €1,500 — high margin.", 3),
      ev("visibleTension", "web", "Website audit", "Beautiful clinic interior but a generic template site that screams 2018.", 2, "https://dermanorte.example.es"),
      ev("activePainSignal", "review", "Google reviews", "Several reviews mention confusion about pricing and which treatment to choose.", 2),
      ev("transitionSignal", "instagram", "Instagram", "Recently added two new practitioners (story highlights).", 2),
    ],
    tensions: ["quality_perception", "price_communication"],
    thesis: "This company is likely losing premium bookings because it has not yet solved the mismatch between a luxury in-clinic experience and a budget-looking digital presence.",
    summary: "An aesthetic-medicine clinic with a luxurious physical experience presents online through a dated template. New practitioners just joined. The perception gap is suppressing the premium pricing the clinic could command.",
    whyNow: "Two new practitioners need a patient pipeline; the moment to upgrade perception is as capacity grows.",
    whyBeforeOthers: "High margin and a named owner-physician, but timing is softer than the top leads — hence ranked below them.",
    blindSpot: "The cheap-looking site is anchoring patients' price expectations below what the clinic is worth.",
    firstLever: "Premium brand system + repositioned site that matches the in-clinic experience.",
    offer: "reposition",
    callOpening: "Tu clínica por dentro es de otro nivel — pero la web no lo cuenta. ¿Te has planteado lo que eso te cuesta en percepción de precio?",
    objection: "La web nos funciona bien por ahora.",
    objectionResponse: "Funciona para los que ya te conocen. Te enseño qué pasa con el paciente nuevo que te compara — ahí es donde se decide el ticket.",
    reasonsNotToCall: ["No hard timing trigger this week.", "Owner may not feel the pain yet if the clinic is full."],
    invalidators: ["The clinic is already at capacity and turning patients away.", "A rebrand is already underway."],
  }),

  // ------------------------------------------------------------ REAL ESTATE
  mk({
    id: "re-nordluz-promotor",
    company: "Nordluz Living",
    sector: "realestate",
    subsector: "Boutique residential developer / promotor",
    city: "Málaga",
    region: "Andalucía",
    website: "https://nordluz.example.es",
    instagram: "@nordluz.living",
    linkedin: "company/nordluz-living",
    googleMaps: "https://maps.example/nordluz",
    phone: "+34 951 10 20 30",
    email: "info@nordluz.example.es",
    dm: { name: "Sergio Valle", role: "Founder / CEO", linkedin: "in/sergio-valle-nordluz" },
    S: "GGGGGGGGGG",
    evidence: [
      ev("transitionSignal", "press", "Real-estate press", "Launched a new 38-unit branded residences project on the Costa del Sol this quarter.", 3, "https://press.example/nordluz-launch"),
      ev("whyNow", "press", "Real-estate press", "Sales phase opens next month — they need premium positioning *now*.", 3),
      ev("visibleTension", "web", "Website audit", "€600k+ units sold through a generic property-listing template with stock photos.", 3, "https://nordluz.example.es"),
      ev("economicCapacity", "press", "Real-estate press", "International buyer target, multi-million-euro project pipeline.", 3),
      ev("reachableDecisionMaker", "linkedin", "LinkedIn", "Founder is active on LinkedIn, posts about the project personally.", 3, "https://linkedin.example/sergio-valle"),
      ev("budgetPriority", "inference", "Analysis", "A single unsold unit dwarfs any branding fee — perception directly affects sales velocity.", 2),
    ],
    tensions: ["price_communication", "ambition_maturity", "visibility_conversion"],
    thesis: "This company is likely delaying sales velocity on a multi-million-euro project because it has not yet solved the gap between a luxury product and a commodity-grade digital presentation.",
    summary: "A boutique developer is opening the sales phase of a 38-unit branded-residences project aimed at international buyers — through a stock-photo template site. At €600k+ per unit, every week of weak positioning is expensive. The founder is reachable and personally invested.",
    whyNow: "The sales phase opens next month. The window to fix positioning before the launch spend is now.",
    whyBeforeOthers: "Ten green signals: timing, capacity, tension, reachable founder and budget priority all align. This is the cleanest XN-grade opportunity on the list.",
    blindSpot: "They likely see the website as a brochure, not as the highest-leverage point in a €20M+ sales funnel.",
    firstLever: "Project brand world + sales-phase positioning and a buyer-grade digital experience.",
    offer: "xn_transformation",
    callOpening: "Sergio, vi el lanzamiento de la promoción — felicidades. Una pregunta directa: ¿la web con la que sale a venta está a la altura del precio por unidad?",
    objection: "Tenemos una inmobiliaria que lleva la comercialización.",
    objectionResponse: "Perfecto, ellos venden — nosotros hacemos que el producto se perciba como lo que vale antes de que lleguen. Es lo que sube el precio de cierre, no el número de visitas.",
    reasonsNotToCall: ["Could have a marketing partner tied to the developer.", "Founder may delegate entirely to the sales agency."],
    invalidators: ["A premium brand campaign is already commissioned for the launch.", "Units are pre-sold and positioning is moot."],
  }),

  mk({
    id: "re-estudio-cardinal",
    company: "Estudio Cardinal Arquitectura",
    sector: "realestate",
    subsector: "Premium architecture & interior design studio",
    city: "Barcelona",
    region: "Cataluña",
    website: "https://estudiocardinal.example.es",
    instagram: "@estudiocardinal",
    linkedin: "company/estudio-cardinal",
    googleMaps: "https://maps.example/cardinal",
    phone: "+34 932 44 55 66",
    email: "estudio@estudiocardinal.example.es",
    dm: { name: "Núria Camps", role: "Principal Architect / Partner", linkedin: "in/nuria-camps-arq" },
    S: "GGGGYGYGGG",
    evidence: [
      ev("transitionSignal", "press", "Design press", "Won a regional architecture award this season; portfolio expanding to commercial work.", 3, "https://press.example/cardinal-award"),
      ev("visibleTension", "web", "Website audit", "Award-winning work shown on a slow, image-heavy site with no project case studies.", 3),
      ev("economicCapacity", "directory", "Directory", "Works on high-end residential + hospitality interiors — strong fee base.", 2),
      ev("whyNow", "press", "Design press", "Award coverage is live — perfect moment to convert recognition into positioning.", 2),
      ev("strategicFit", "inference", "Analysis", "Beautiful portfolio = ideal before/after case study for 01.", 3),
    ],
    tensions: ["quality_perception", "visibility_conversion"],
    thesis: "This company is likely underusing fresh award recognition because it has not yet solved the translation of great work into a positioning and case-study system that wins bigger commissions.",
    summary: "An award-winning architecture studio is expanding into commercial work but presents on a slow site with no case studies. The recognition is peaking now. The opportunity is to convert that moment into a positioning asset before it fades.",
    whyNow: "Award coverage is live this season — recognition is at its most monetisable right now.",
    whyBeforeOthers: "Exceptional case-study potential and clear tension, slightly behind the top leads on hard timing urgency.",
    blindSpot: "Awards fade; without a case-study system the recognition won't compound into commercial commissions.",
    firstLever: "Case-study-driven repositioning + a fast, portfolio-grade site.",
    offer: "reposition",
    callOpening: "Enhorabuena por el premio. Lo vais a aprovechar para entrar en comercial — ¿tenéis la web preparada para contar esos proyectos como casos, no como galería?",
    objection: "Nuestro trabajo habla por sí solo.",
    objectionResponse: "Lo hace con quien ya lo ve. El cliente comercial compra proceso y confianza — eso hay que contarlo. Os enseño cómo, sin tocar vuestra estética.",
    reasonsNotToCall: ["Architects can be protective of their visual identity.", "Project-based revenue can be lumpy — budget timing uncertain."],
    invalidators: ["They already have a case-study system in production.", "Commercial expansion is on hold."],
  }),

  mk({
    id: "re-construcciones-tajo",
    company: "Construcciones Tajo Sur",
    sector: "realestate",
    subsector: "Mid-market construction contractor",
    city: "Toledo",
    region: "Castilla-La Mancha",
    website: "https://construccionestajosur.example.es",
    instagram: null,
    linkedin: "company/construcciones-tajo-sur",
    googleMaps: "https://maps.example/tajosur",
    phone: "+34 925 33 22 11",
    email: "info@construccionestajosur.example.es",
    dm: { name: null, role: "Unknown", linkedin: null },
    S: "YYYRRXRYYR",
    evidence: [
      ev("economicCapacity", "directory", "Directory", "Mid-size contractor, steady public-works pipeline.", 2),
      ev("visibleTension", "web", "Website audit", "Dated site, but B2B/public-sector clients rarely choose on brand.", 1),
    ],
    tensions: ["growth_structure"],
    thesis: "This company is likely fine without us because its revenue does not depend on brand perception or digital conversion.",
    summary: "A mid-market contractor with a dated site and steady public-works revenue. No transition signal, no reachable decision maker, no active pain tied to brand. Included to show the funnel rejecting a low-fit candidate.",
    whyNow: "No timing trigger. There is no reason this week.",
    whyBeforeOthers: "It should NOT rank above others — this is a demonstration of a correct downgrade.",
    blindSpot: "n/a — likely no actionable lever for 01/XN.",
    firstLever: "None clearly identifiable.",
    offer: "audit",
    callOpening: "—",
    objection: "No necesitamos marketing, trabajamos por concurso.",
    objectionResponse: "Entendido — no es vuestro momento. (Discard.)",
    reasonsNotToCall: ["Revenue independent of brand.", "No reachable decision maker.", "No timing trigger.", "Public-sector buying ignores positioning."],
    invalidators: ["They are pivoting to private premium clients (would change everything)."],
  }),

  // ------------------------------------------------------------------ GROWTH
  mk({
    id: "g-ferment-labs",
    company: "Ferment Labs",
    sector: "growth",
    subsector: "Funded food-tech / fermentation brand",
    city: "Madrid",
    region: "Madrid",
    website: "https://fermentlabs.example.com",
    instagram: "@ferment.labs",
    linkedin: "company/ferment-labs",
    googleMaps: null,
    phone: "+34 911 44 55 66",
    email: "hello@fermentlabs.example.com",
    dm: { name: "Clara Bonet", role: "Co-founder / CEO", linkedin: "in/clara-bonet" },
    S: "GGGGGGGGYG",
    evidence: [
      ev("transitionSignal", "funding", "Funding news", "Closed a €1.2M seed round announced 6 weeks ago.", 3, "https://press.example/ferment-seed"),
      ev("whyNow", "funding", "Funding news", "Post-raise = pressure to deploy capital into growth and brand right now.", 3),
      ev("activePainSignal", "jobs", "Job board", "Hiring a growth marketer and a brand designer simultaneously.", 3, "https://jobs.example/ferment"),
      ev("visibleTension", "web", "Website audit", "Series-stage ambition on a Webflow template that still has placeholder copy.", 2),
      ev("economicCapacity", "funding", "Funding news", "Fresh capital earmarked partly for brand/marketing per the announcement.", 3),
      ev("reachableDecisionMaker", "linkedin", "LinkedIn", "CEO actively posting about hiring and the raise.", 3),
    ],
    tensions: ["growth_structure", "ambition_maturity", "expansion_systems"],
    thesis: "This company is likely about to overspend on internal hires because it has not yet solved its brand and positioning foundation post-raise.",
    summary: "A food-tech brand closed a €1.2M seed six weeks ago and is hiring growth + brand roles, yet runs on a placeholder Webflow template. Capital is allocated and the founder is reachable. The moment to set the foundation is before the hires arrive.",
    whyNow: "Six weeks post-raise — capital is being deployed this quarter and the brand foundation isn't set.",
    whyBeforeOthers: "Funded + actively hiring + reachable founder = a fundable, fast-moving opportunity with both 01 and XN paths.",
    blindSpot: "Hiring brand talent onto no foundation produces inconsistency, not brand — a system should come first.",
    firstLever: "Brand foundation + positioning system the new hires build on.",
    offer: "xn_transformation",
    callOpening: "Clara, enhorabuena por la ronda. Antes de que entren los perfiles de marca y growth, ¿tienen ya un sistema sobre el que ejecutar o van a improvisarlo?",
    objection: "Vamos a montar el equipo interno primero.",
    objectionResponse: "Eso es exactamente por qué llamamos ahora: para que ese equipo entre a ejecutar una base sólida y no a inventarla mientras gastan ronda.",
    reasonsNotToCall: ["Investors may have a preferred agency.", "Founder bandwidth is thin right after a raise."],
    invalidators: ["A brand studio is already engaged for the post-raise sprint.", "The placeholder site is a known temporary stopgap with a fix dated."],
  }),

  mk({
    id: "g-rutaverde-logistics",
    company: "RutaVerde Logística",
    sector: "growth",
    subsector: "Last-mile green logistics scale-up",
    city: "Sevilla",
    region: "Andalucía",
    website: "https://rutaverde.example.com",
    instagram: "@rutaverde",
    linkedin: "company/rutaverde",
    googleMaps: null,
    phone: "+34 954 77 88 99",
    email: "contacto@rutaverde.example.com",
    dm: { name: "Diego Mota", role: "COO", linkedin: "in/diego-mota-rutaverde" },
    S: "GGYGGGYGYG",
    evidence: [
      ev("transitionSignal", "press", "Business press", "Expanded to two new cities this year; headcount up 40% on LinkedIn.", 3, "https://press.example/rutaverde-expand"),
      ev("activePainSignal", "jobs", "Job board", "Hiring sales + ops roles; no marketing function visible.", 2),
      ev("whyNow", "press", "Business press", "City expansion announced this quarter.", 2),
      ev("visibleTension", "web", "Website audit", "Scaling B2B operation with a thin one-page site, no case studies, weak lead capture.", 2),
      ev("budgetPriority", "inference", "Analysis", "B2B sales pipeline directly affected by weak positioning.", 2),
    ],
    tensions: ["growth_structure", "expansion_systems", "visibility_conversion"],
    thesis: "This company is likely losing B2B pipeline because it has not yet solved a positioning and lead-capture system to match its operational expansion.",
    summary: "A green-logistics scale-up expanded to two new cities and grew headcount 40%, but its web presence is a thin one-pager with weak lead capture. Operations are scaling faster than commercial infrastructure.",
    whyNow: "City expansion this quarter means the sales motion is being rebuilt — the right moment for positioning + capture.",
    whyBeforeOthers: "Strong growth and clear lever, but the decision maker (COO) is one step from marketing ownership — slightly softer than top leads.",
    blindSpot: "Operational growth is masking a commercial-conversion gap that will bite when expansion plateaus.",
    firstLever: "B2B positioning + lead-capture funnel and a CRM-ready intake.",
    offer: "web_funnel",
    callOpening: "Diego, vi la expansión a dos ciudades — enhorabuena. ¿Cómo estáis capturando demanda B2B en los mercados nuevos ahora mismo?",
    objection: "Crecemos por boca a boca y comercial directo.",
    objectionResponse: "Funciona hasta que dejáis de estar en la sala. Os montamos el sistema que captura lo que el comercial no llega a tocar.",
    reasonsNotToCall: ["B2B logistics may convert on relationships, not brand.", "Marketing ownership unclear."],
    invalidators: ["They already run a working B2B funnel + CRM.", "Expansion is paused."],
  }),

  mk({
    id: "g-saas-quoria",
    company: "Quoria (HR SaaS)",
    sector: "growth",
    subsector: "Early-stage B2B SaaS",
    city: "Valencia",
    region: "Comunidad Valenciana",
    website: "https://quoria.example.com",
    instagram: null,
    linkedin: "company/quoria",
    googleMaps: null,
    phone: null,
    email: "team@quoria.example.com",
    dm: { name: "Unknown", role: "Unknown", linkedin: null },
    S: "GYYYXYRYYX",
    evidence: [
      ev("transitionSignal", "press", "Startup press", "Mentioned in an accelerator cohort announcement this year.", 2),
      ev("visibleTension", "web", "Website audit", "Generic SaaS template, unclear value proposition.", 2),
    ],
    tensions: ["ambition_maturity"],
    thesis: "This company might be too early and too unreachable to prioritise; positioning help is plausible but evidence is thin.",
    summary: "An early-stage SaaS in an accelerator with a generic site. No named decision maker, no direct contact, weak budget signals. Included to show a 'possibility, not hypothesis' lead being held back by the 3-evidence rule.",
    whyNow: "Accelerator timing is a weak trigger; no concrete capital or hiring evidence.",
    whyBeforeOthers: "Should rank low — only two evidence points, below the shortlist threshold.",
    blindSpot: "Likely a positioning/messaging gap, but unverified.",
    firstLever: "Positioning sprint (if reachable).",
    offer: "reposition",
    callOpening: "—",
    objection: "Somos pre-seed, no hay presupuesto.",
    objectionResponse: "Comprendido — os mantenemos como secundario hasta que cerréis ronda.",
    reasonsNotToCall: ["No named decision maker.", "No direct contact.", "Only 2 evidence points.", "Budget likely absent pre-seed."],
    invalidators: ["They just closed a round and named a CEO contact (would re-qualify)."],
  }),

  // ------------------------------------------------------------- HOSPITALITY
  mk({
    id: "ho-casa-lumen",
    company: "Casa Lumen Boutique Hotel",
    sector: "hospitality",
    subsector: "Boutique hotel",
    city: "San Sebastián",
    region: "País Vasco",
    website: "https://casalumen.example.es",
    instagram: "@casalumen",
    linkedin: "company/casa-lumen",
    googleMaps: "https://maps.example/casalumen",
    phone: "+34 943 11 22 33",
    email: "reservas@casalumen.example.es",
    dm: { name: "Aitor Iruretagoyena", role: "Owner / General Manager", linkedin: "in/aitor-irureta" },
    S: "GGGGGGGGGY",
    evidence: [
      ev("transitionSignal", "press", "Travel press", "Reopened after a full renovation this spring; added a rooftop restaurant.", 3, "https://press.example/casalumen-reopen"),
      ev("whyNow", "press", "Travel press", "Reopening + summer season = peak demand window starting now.", 3),
      ev("visibleTension", "web", "Website audit", "Renovated property still using pre-renovation photos and an OTA-dependent booking flow.", 3),
      ev("economicCapacity", "directory", "Directory", "Boutique room rates €220+/night, new F&B revenue line.", 3),
      ev("activePainSignal", "review", "Booking reviews", "Guests note the website doesn't reflect the new look; direct booking is clunky.", 2),
      ev("budgetPriority", "inference", "Analysis", "Every direct booking saved from OTA commission funds the work quickly.", 2),
    ],
    tensions: ["quality_perception", "visibility_conversion", "expansion_systems"],
    thesis: "This company is likely leaking margin to OTAs because it has not yet solved a direct-booking experience that reflects its post-renovation product.",
    summary: "A boutique hotel reopened after renovation with a new rooftop restaurant, but its site shows old photos and pushes guests to OTAs. With the summer season starting, every week of weak direct booking is paid in commission. The owner-GM is reachable.",
    whyNow: "Post-renovation reopening into peak summer season — the highest-leverage moment to capture direct bookings.",
    whyBeforeOthers: "Clear timing, strong capacity, OTA-commission math makes ROI self-evident, reachable owner.",
    blindSpot: "The renovation ROI is being quietly taxed by OTA commissions a direct-booking experience would recover.",
    firstLever: "Post-renovation site + direct-booking experience and a rooftop F&B story.",
    offer: "web_funnel",
    callOpening: "Aitor, vi la reapertura tras la reforma — espectacular. La web todavía enseña el hotel de antes. ¿Cuánto se está yendo en comisiones de OTA esta temporada?",
    objection: "Booking y las OTAs nos llenan igual.",
    objectionResponse: "Te llenan, pero a coste. Te enseño la cuenta de comisión de un verano frente a lo que cuesta recuperar la reserva directa — la diferencia es el proyecto.",
    reasonsNotToCall: ["High season may mean no bandwidth to start now.", "Could be locked into an OTA-heavy strategy."],
    invalidators: ["They already run a strong direct-booking engine.", "New site is already in progress."],
  }),

  mk({
    id: "ho-brasa-altamar",
    company: "Brasa Altamar",
    sector: "hospitality",
    subsector: "Premium coastal restaurant group",
    city: "Alicante",
    region: "Comunidad Valenciana",
    website: "https://brasaaltamar.example.es",
    instagram: "@brasa.altamar",
    linkedin: null,
    googleMaps: "https://maps.example/brasaaltamar",
    phone: "+34 965 22 33 44",
    email: "eventos@brasaaltamar.example.es",
    dm: { name: "Rocío Server", role: "Owner", linkedin: "in/rocio-server" },
    S: "GGGGGGYGGY",
    evidence: [
      ev("transitionSignal", "instagram", "Instagram", "Announced a second venue (rooftop concept) opening this season.", 3, "https://instagram.example/brasaaltamar"),
      ev("whyNow", "instagram", "Instagram", "Second-venue opening announced for next month.", 3),
      ev("economicCapacity", "review", "Reviews / menu", "High average ticket, events + private dining revenue.", 3),
      ev("visibleTension", "web", "Website audit", "No real website — Instagram-only, reservations via DM, no events landing page.", 3),
      ev("activePainSignal", "review", "Google reviews", "Reviews mention difficulty booking events and slow DM responses.", 2),
    ],
    tensions: ["growth_structure", "visibility_conversion", "expansion_systems"],
    thesis: "This company is likely losing high-margin events bookings because it has not yet solved a proper web + reservation/events capture beyond Instagram DMs.",
    summary: "A premium coastal restaurant is opening a second rooftop venue while running entirely on Instagram with DM-based reservations. Reviews already flag event-booking friction. Two venues on a DM funnel will compound the leakage.",
    whyNow: "A second venue opens next month — the DM-only system won't scale to two locations.",
    whyBeforeOthers: "High-margin events revenue, clear tension and timing; LinkedIn absent so decision-maker reach is via Instagram (slightly softer).",
    blindSpot: "The Instagram-only model that worked for one venue will silently cap the second venue's events revenue.",
    firstLever: "Web + events/reservation capture replacing DM-based booking.",
    offer: "web_funnel",
    callOpening: "Rocío, vi que abrís el rooftop — enhorabuena. Con dos sitios, ¿vais a seguir gestionando reservas y eventos por DM?",
    objection: "Instagram nos funciona de maravilla.",
    objectionResponse: "Para un sitio, sí. Para dos y con eventos, el DM se convierte en cuello de botella. Te enseño cuántos eventos se pierden esperando respuesta.",
    reasonsNotToCall: ["Owner may believe Instagram is enough.", "Restaurant margins can be tight despite high ticket."],
    invalidators: ["They already have an events booking system.", "Second venue is delayed/cancelled."],
  }),

  mk({
    id: "ho-rooftop-mira",
    company: "Mira Sky Bar",
    sector: "hospitality",
    subsector: "Rooftop / experiential bar",
    city: "Granada",
    region: "Andalucía",
    website: "https://mirarooftop.example.es",
    instagram: "@mira.skybar",
    linkedin: null,
    googleMaps: "https://maps.example/mirarooftop",
    phone: "+34 958 44 55 66",
    email: "info@mirarooftop.example.es",
    dm: { name: "Pol Adell", role: "Co-owner", linkedin: null },
    S: "YGYYYYYRYY",
    evidence: [
      ev("economicCapacity", "review", "Reviews", "Premium cocktail pricing, popular sunset slot.", 2),
      ev("visibleTension", "web", "Website audit", "Site exists but is slow and not mobile-optimised; bookings via phone only.", 2),
      ev("transitionSignal", "instagram", "Instagram", "Hinted at a winter indoor concept but nothing concrete.", 1),
    ],
    tensions: ["visibility_conversion", "quality_perception"],
    thesis: "This company might benefit from a booking/experience upgrade, but the timing trigger and budget priority are weak.",
    summary: "A rooftop bar with premium pricing and a slow, phone-only booking site. Some tension exists, but no concrete transition and a likely thin budget. Sits in the secondary tier.",
    whyNow: "Only a vague winter-concept hint — no firm trigger.",
    whyBeforeOthers: "Ranks mid: real tension but soft timing and questionable budget priority.",
    blindSpot: "Mobile booking friction at the exact moment (on-phone, planning a night out) costs covers.",
    firstLever: "Fast mobile booking page + experience-led positioning.",
    offer: "audit",
    callOpening: "Pol, el sitio es top pero la web va lenta en el móvil — justo cuando la gente reserva. ¿Lo habéis mirado?",
    objection: "Vamos llenos sin web.",
    objectionResponse: "Hoy sí. Te dejo un mini-audit gratis de lo que pierdes en móvil; si no hay nada, no insisto.",
    reasonsNotToCall: ["Likely tight margins.", "No firm timing.", "Budget priority questionable."],
    invalidators: ["The winter concept becomes real and funded.", "They're already redesigning."],
  }),

  // ----------------------------------------- ADDITIONAL MIXED-TIER CANDIDATES
  mk({
    id: "h-fisio-anaya",
    company: "Centro Anaya Fisioterapia",
    sector: "health",
    subsector: "Physiotherapy / rehab clinic",
    city: "Salamanca",
    region: "Castilla y León",
    website: "https://centroanaya.example.es",
    instagram: "@centro.anaya",
    linkedin: null,
    googleMaps: "https://maps.example/centroanaya",
    phone: "+34 923 11 00 22",
    email: "cita@centroanaya.example.es",
    dm: { name: "Elena Marcos", role: "Owner / Lead Physio", linkedin: "in/elena-marcos-fisio" },
    S: "YYGGGYGGYY",
    evidence: [
      ev("activePainSignal", "review", "Google reviews", "Strong clinical reviews but repeated complaints about phone-only booking and waiting.", 3, "https://maps.example/anaya-reviews"),
      ev("actionableLever", "web", "Website audit", "No online booking; site is a brochure with outdated hours.", 2),
      ev("visibleTension", "review", "Reviews", "4.8★ clinical trust vs amateurish digital presence.", 2),
      ev("economicCapacity", "directory", "Directory", "Established single location, steady but not premium pricing.", 2),
    ],
    tensions: ["quality_perception", "visibility_conversion"],
    thesis: "This company is likely losing easy bookings because it has not yet solved online appointment capture despite high clinical trust.",
    summary: "A well-reviewed physio clinic with strong clinical trust but phone-only booking and a brochure site. Pain is active in reviews. A clean, fundable 01 audit/landing engagement — though capacity is mid-tier.",
    whyNow: "No sharp trigger, but the booking pain is chronic and visible — a mini-audit can manufacture the moment.",
    whyBeforeOthers: "Solid active pain and clear lever, but mid economic capacity keeps it below premium leads.",
    blindSpot: "High trust is being wasted at the booking step — the easiest patients to win are bouncing on friction.",
    firstLever: "Online booking + a simple conversion landing page.",
    offer: "reposition",
    callOpening: "Elena, tus reseñas clínicas son excelentes — pero varias mencionan lo difícil que es pedir cita. ¿Sabes cuántos pacientes pierdes ahí?",
    objection: "Las citas las llevamos por teléfono y va bien.",
    objectionResponse: "Va bien con quien insiste. El paciente nuevo que no coge el teléfono se va a otra clínica. Te lo cuantifico en un mini-audit.",
    reasonsNotToCall: ["Mid budget — may resist €3k.", "Single owner, limited bandwidth."],
    invalidators: ["They add online booking themselves.", "Clinic is at capacity."],
  }),

  mk({
    id: "re-habitat-prime",
    company: "Habitat Prime Inmobiliaria",
    sector: "realestate",
    subsector: "Luxury real-estate agency",
    city: "Marbella",
    region: "Andalucía",
    website: "https://habitatprime.example.es",
    instagram: "@habitatprime",
    linkedin: "company/habitat-prime",
    googleMaps: "https://maps.example/habitatprime",
    phone: "+34 952 00 11 22",
    email: "info@habitatprime.example.es",
    dm: { name: "Tomás Reig", role: "Managing Director", linkedin: "in/tomas-reig" },
    S: "GGGGYGGGGY",
    evidence: [
      ev("transitionSignal", "linkedin", "LinkedIn", "Hired three new agents and opened a second office (Puerto Banús) this year.", 3, "https://linkedin.example/habitatprime"),
      ev("economicCapacity", "web", "Listings", "Luxury listings €1M–€8M, international clientele.", 3),
      ev("visibleTension", "web", "Website audit", "High-value listings on a dated, slow portal-style site with poor English/Spanish parity.", 3),
      ev("whyNow", "linkedin", "LinkedIn", "Second office just opened — brand consistency now matters across locations.", 2),
      ev("reachableDecisionMaker", "linkedin", "LinkedIn", "MD active and reachable.", 2),
    ],
    tensions: ["price_communication", "expansion_systems", "visibility_conversion"],
    thesis: "This company is likely losing international high-net-worth leads because it has not yet solved a bilingual, premium digital experience matching its luxury inventory.",
    summary: "A luxury Marbella agency opened a second office and hired agents, but presents €1M+ listings through a dated portal with weak bilingual parity. International buyers judge fast on perception. A strong 01/XN candidate.",
    whyNow: "A second office just opened — brand consistency and a premium lead experience matter across both now.",
    whyBeforeOthers: "Luxury capacity and reachable MD, ranks just behind leads with sharper single-moment timing.",
    blindSpot: "International HNW buyers screen agencies on digital polish before a single call — the site is filtering them out silently.",
    firstLever: "Premium bilingual web experience + lead-routing across both offices.",
    offer: "web_funnel",
    callOpening: "Tomás, enhorabuena por Puerto Banús. Con cliente internacional de 1 a 8 millones, ¿la web actual transmite ese nivel en inglés y español?",
    objection: "Trabajamos con portales (Idealista, etc.).",
    objectionResponse: "Los portales generan el lead; vuestra web decide si confía en vosotros frente a la competencia. Ahí se gana el mandato exclusivo.",
    reasonsNotToCall: ["Agencies often rely on portals over own brand.", "May have in-house marketing."],
    invalidators: ["A premium bilingual site is already live.", "They close purely on portal volume."],
  }),

  mk({
    id: "g-cosmetics-aurora",
    company: "Aurora Skin Co.",
    sector: "growth",
    subsector: "DTC clean-beauty brand",
    city: "Barcelona",
    region: "Cataluña",
    website: "https://auroraskin.example.com",
    instagram: "@auroraskin.co",
    linkedin: "company/aurora-skin",
    googleMaps: null,
    phone: null,
    email: "founders@auroraskin.example.com",
    dm: { name: "Marina Solé", role: "Founder", linkedin: "in/marina-sole" },
    S: "GGYGGGGYYG",
    evidence: [
      ev("transitionSignal", "press", "Retail press", "Just landed shelf space in a national pharmacy chain.", 3, "https://press.example/aurora-retail"),
      ev("whyNow", "press", "Retail press", "Retail launch this month — brand visibility at point of sale now critical.", 3),
      ev("activePainSignal", "instagram", "Instagram", "Posting cadence dropped sharply during the retail push (overstretched founder).", 2),
      ev("economicCapacity", "inference", "Analysis", "National retail distribution implies real revenue and margin.", 2),
      ev("visibleTension", "web", "Website audit", "DTC site doesn't reflect the new retail credibility; no 'as seen in' or retail story.", 2),
    ],
    tensions: ["growth_structure", "ambition_maturity", "expansion_systems"],
    thesis: "This company is likely under-converting its new retail credibility because it has not yet solved the brand narrative connecting DTC and retail channels.",
    summary: "A clean-beauty brand just won national pharmacy shelf space, but its DTC site and social haven't caught up and posting has lapsed during the push. The retail win is a credibility asset not yet being used.",
    whyNow: "Retail launch is this month — point-of-sale visibility and an omni-channel story matter immediately.",
    whyBeforeOthers: "Clear transition and lever; founder reachable. Slightly behind on direct-contact channels (email only).",
    blindSpot: "Retail credibility is the strongest trust asset they have and it's invisible on their own channels.",
    firstLever: "Omni-channel brand narrative + content system bridging retail and DTC.",
    offer: "reposition",
    callOpening: "Marina, enhorabuena por entrar en farmacias — eso es credibilidad enorme. ¿La estáis contando en vuestra web y redes? Vi que el ritmo bajó.",
    objection: "Estamos enfocados en el sell-through en tienda.",
    objectionResponse: "Exacto — y el sell-through sube cuando el cliente que ve el producto en la farmacia os encuentra y os reconoce online. Eso es lo que montamos.",
    reasonsNotToCall: ["Founder fully absorbed by retail ops.", "May not have email-reachable budget owner."],
    invalidators: ["They have an agency on the retail launch.", "Social lapse is temporary and intentional."],
  }),

  mk({
    id: "ho-finca-olivar",
    company: "Finca El Olivar Eventos",
    sector: "hospitality",
    subsector: "Premium events / weddings venue",
    city: "Córdoba",
    region: "Andalucía",
    website: "https://fincaelolivar.example.es",
    instagram: "@finca.elolivar",
    linkedin: null,
    googleMaps: "https://maps.example/fincaelolivar",
    phone: "+34 957 33 44 55",
    email: "bodas@fincaelolivar.example.es",
    dm: { name: "Carmen Pineda", role: "Owner / Events Director", linkedin: "in/carmen-pineda" },
    S: "YGGGGYGGGY",
    evidence: [
      ev("economicCapacity", "web", "Pricing inference", "Premium wedding venue — events worth €15k–€40k each.", 3),
      ev("activePainSignal", "review", "Reviews / forms", "Couples mention slow/confusing inquiry responses and no clear package info.", 2),
      ev("visibleTension", "web", "Website audit", "Stunning venue, but inquiry is a single generic form; no gallery-to-inquiry funnel.", 3),
      ev("whyNow", "instagram", "Instagram", "Booking season for next year opens now — peak inquiry window.", 2),
    ],
    tensions: ["quality_perception", "visibility_conversion"],
    thesis: "This company is likely losing high-value event bookings because it has not yet solved a structured inquiry-to-booking funnel during peak inquiry season.",
    summary: "A premium events venue with €15k–€40k events runs inquiries through one generic form and slow responses. Booking season for next year is opening now — the highest-inquiry window of the year.",
    whyNow: "Next-year booking season opens now — inquiry volume peaks and the funnel is weakest exactly when it matters.",
    whyBeforeOthers: "Very high per-event value and clear funnel lever; timing is seasonal rather than a single sharp event.",
    blindSpot: "One slow inquiry response in peak season can lose a €30k booking to a faster venue.",
    firstLever: "Inquiry-to-booking funnel with package clarity + automated first response.",
    offer: "web_funnel",
    callOpening: "Carmen, arranca la temporada de reservas para el año que viene. Con bodas de 15 a 40 mil euros, ¿cómo gestionáis las consultas que entran ahora?",
    objection: "Respondemos a todas las consultas personalmente.",
    objectionResponse: "Y eso es vuestro valor — pero la pareja que no recibe respuesta en horas ya está hablando con otra finca. Automatizamos la primera respuesta para que la personal llegue a tiempo.",
    reasonsNotToCall: ["Seasonal cashflow may delay budget.", "Owner may equate automation with losing the personal touch."],
    invalidators: ["They already run a structured inquiry funnel.", "Venue is fully booked for next year."],
  }),

  mk({
    id: "g-edtech-lumina",
    company: "Lumina Learning",
    sector: "growth",
    subsector: "EdTech scale-up",
    city: "Madrid",
    region: "Madrid",
    website: "https://luminalearning.example.com",
    instagram: "@lumina.learning",
    linkedin: "company/lumina-learning",
    googleMaps: null,
    phone: null,
    email: "press@luminalearning.example.com",
    dm: { name: "Unknown", role: "Marketing (generic)", linkedin: null },
    S: "GYYYXYRYYX",
    evidence: [
      ev("transitionSignal", "press", "Press", "Announced expansion to LatAm markets this year.", 2),
      ev("visibleTension", "web", "Website audit", "Inconsistent messaging between regions, dated landing pages.", 2),
    ],
    tensions: ["ambition_maturity", "expansion_systems"],
    thesis: "This company may have a positioning gap, but the decision maker is unreachable and evidence is thin.",
    summary: "An EdTech expanding to LatAm with inconsistent messaging. Only a generic press contact, two evidence points. Held below shortlist by the 3-evidence rule — a 'possibility', not a 'hypothesis'.",
    whyNow: "Expansion is a soft trigger; no concrete capital/hiring evidence found.",
    whyBeforeOthers: "Ranks low — insufficient evidence and no reachable decision maker.",
    blindSpot: "Likely a multi-region messaging-consistency problem.",
    firstLever: "Messaging architecture across regions (if reachable).",
    offer: "reposition",
    callOpening: "—",
    objection: "Tenemos equipo de marketing interno.",
    objectionResponse: "Entendido — sin contacto directo lo dejamos como secundario.",
    reasonsNotToCall: ["No named decision maker.", "Only 2 evidence points.", "Generic contact only."],
    invalidators: ["A named growth lead becomes reachable.", "Funding/hiring evidence surfaces."],
  }),

  mk({
    id: "h-ginecologia-vida",
    company: "Clínica Vida Salud de la Mujer",
    sector: "health",
    subsector: "Women's health / gynaecology clinic",
    city: "Zaragoza",
    region: "Aragón",
    website: "https://clinicavida.example.es",
    instagram: "@clinicavida",
    linkedin: "company/clinica-vida",
    googleMaps: "https://maps.example/clinicavida",
    phone: "+34 976 22 11 33",
    email: "direccion@clinicavida.example.es",
    dm: { name: "Dra. Pilar Used", role: "Medical Director / Owner", linkedin: "in/pilar-used" },
    S: "GGGGYGGGGY",
    evidence: [
      ev("transitionSignal", "press", "Local press", "Added a fertility unit and two specialists this year.", 3, "https://press.example/vida-fertility"),
      ev("economicCapacity", "web", "Services", "Fertility treatments = very high-ticket, repeat-cycle patients.", 3),
      ev("visibleTension", "web", "Website audit", "New high-trust service launched on a site with no dedicated fertility journey or trust content.", 3),
      ev("whyNow", "press", "Local press", "Fertility unit launched this quarter.", 2),
      ev("activePainSignal", "review", "Reviews", "Patients want clearer information about processes and costs upfront.", 2),
    ],
    tensions: ["growth_structure", "quality_perception", "visibility_conversion"],
    thesis: "This company is likely under-acquiring high-value fertility patients because it has not yet solved the trust-content and patient-journey architecture a new fertility unit demands.",
    summary: "A women's-health clinic launched a fertility unit — among the highest-trust, highest-ticket medical decisions a patient makes — on a site with no dedicated journey or trust content. The new line needs a different digital approach than the rest of the clinic.",
    whyNow: "The fertility unit launched this quarter and needs patient acquisition built for a high-consideration decision.",
    whyBeforeOthers: "Very high patient value and a reachable medical director; sits just behind the sharpest-timing leads.",
    blindSpot: "Fertility patients research for months — without trust content the clinic is invisible during the decision window.",
    firstLever: "Fertility patient-journey microsite + trust-content system.",
    offer: "web_funnel",
    callOpening: "Dra. Used, enhorabuena por la unidad de fertilidad. Es la decisión más meditada que toma una paciente — ¿la web la acompaña en ese proceso o solo la anuncia?",
    objection: "Tenemos lista de espera, no necesitamos más pacientes.",
    objectionResponse: "Entonces hablemos de la paciente adecuada, no de más volumen. La web bien hecha selecciona y prepara, no solo capta.",
    reasonsNotToCall: ["May already be at capacity.", "Medical sensitivity requires careful content work."],
    invalidators: ["The fertility unit already has dedicated content.", "Clinic is fully booked."],
  }),

  mk({
    id: "re-coliving-norte",
    company: "Nidus Co-Living",
    sector: "realestate",
    subsector: "Co-living / flexible-living operator",
    city: "Bilbao",
    region: "País Vasco",
    website: "https://niduscoliving.example.com",
    instagram: "@nidus.coliving",
    linkedin: "company/nidus-coliving",
    googleMaps: "https://maps.example/nidus",
    phone: "+34 944 00 99 88",
    email: "hola@niduscoliving.example.com",
    dm: { name: "Unai Beitia", role: "Co-founder", linkedin: "in/unai-beitia" },
    S: "GGYGGGGYGY",
    evidence: [
      ev("transitionSignal", "press", "Press", "Opening a third building this year; raised a small round.", 3, "https://press.example/nidus-round"),
      ev("activePainSignal", "web", "Website audit", "Occupancy depends on web conversion; current booking flow is clunky and slow.", 3),
      ev("whyNow", "press", "Press", "Third building opens this quarter — occupancy ramp pressure now.", 2),
      ev("economicCapacity", "inference", "Analysis", "Multi-building operator with fresh capital.", 2),
      ev("visibleTension", "web", "Audit", "Design-forward physical spaces vs generic booking UX.", 2),
    ],
    tensions: ["growth_structure", "expansion_systems", "visibility_conversion"],
    thesis: "This company is likely slowing occupancy ramp because it has not yet solved a conversion-optimised booking experience as it opens a third building.",
    summary: "A co-living operator opening its third building and freshly funded, where occupancy is a direct function of web conversion — yet the booking flow is clunky. The ramp pressure makes conversion an immediate revenue lever.",
    whyNow: "A third building opens this quarter; empty rooms during ramp are pure lost revenue.",
    whyBeforeOthers: "Direct web-to-revenue link and clear timing; reachable founder. Strong mid-to-upper lead.",
    blindSpot: "Every point of booking-flow friction maps directly to vacancy days they're paying for.",
    firstLever: "Conversion-optimised booking experience + occupancy funnel.",
    offer: "web_funnel",
    callOpening: "Unai, abrís el tercer edificio — la ocupación se juega en la web. ¿Cuánto tarda alguien hoy en pasar de ver una habitación a reservarla?",
    objection: "Tenemos lista de espera en los otros edificios.",
    objectionResponse: "En los consolidados sí; el edificio nuevo arranca de cero y cada día vacío cuesta. Ahí es donde la conversión paga el proyecto.",
    reasonsNotToCall: ["Waitlist demand may mask the new-building need.", "Founder bandwidth post-raise."],
    invalidators: ["Booking flow is already optimised.", "Third building is pre-filled."],
  }),

  mk({
    id: "ho-cafe-tostado",
    company: "Tostado Specialty Coffee",
    sector: "hospitality",
    subsector: "Specialty coffee micro-chain",
    city: "Valencia",
    region: "Comunidad Valenciana",
    website: "https://tostadocoffee.example.es",
    instagram: "@tostado.coffee",
    linkedin: null,
    googleMaps: "https://maps.example/tostado",
    phone: "+34 963 00 22 44",
    email: "hola@tostadocoffee.example.es",
    dm: { name: "Bru Esteve", role: "Founder", linkedin: "in/bru-esteve" },
    S: "YYYYXYYRYR",
    evidence: [
      ev("transitionSignal", "instagram", "Instagram", "Opened a third café this year.", 2),
      ev("visibleTension", "web", "Audit", "No e-commerce for beans despite a roastery; site is informational only.", 2),
    ],
    tensions: ["growth_structure", "visibility_conversion"],
    thesis: "This company might have an e-commerce/brand lever, but margins are thin and budget priority is low.",
    summary: "A specialty coffee micro-chain opened a third café with a roastery but no bean e-commerce. Real tension, but café margins are thin and budget priority is questionable — a secondary lead at best.",
    whyNow: "Third-café opening is a soft trigger; no urgent revenue pressure tied to brand.",
    whyBeforeOthers: "Ranks low: thin margins and weak budget priority despite a plausible lever.",
    blindSpot: "The roastery could sell beans online at high margin — currently leaving that channel on the table.",
    firstLever: "Bean e-commerce + brand store (small first step).",
    offer: "audit",
    callOpening: "Bru, tenéis tostadero pero no vendéis grano online — ¿por qué no?",
    objection: "Los cafés ya nos dan trabajo de sobra.",
    objectionResponse: "Lo entiendo. Os dejo la idea y un mini-audit; si no encaja ahora, lo retomamos.",
    reasonsNotToCall: ["Thin café margins.", "Budget priority low.", "Founder time-poor."],
    invalidators: ["They commit to a roastery/wholesale growth push.", "A funding event changes capacity."],
  }),

  mk({
    id: "h-veterinaria-altos",
    company: "Hospital Veterinario Altos",
    sector: "health",
    subsector: "24h veterinary hospital",
    city: "Murcia",
    region: "Murcia",
    website: "https://vetaltos.example.es",
    instagram: "@vet.altos",
    linkedin: "company/vet-altos",
    googleMaps: "https://maps.example/vetaltos",
    phone: "+34 968 11 22 33",
    email: "info@vetaltos.example.es",
    dm: { name: "Dr. Ramón Gil", role: "Director", linkedin: "in/ramon-gil-vet" },
    S: "GGGGGGYGGY",
    evidence: [
      ev("transitionSignal", "press", "Local press", "Expanded to a 24h emergency service and a second branch this year.", 3, "https://press.example/vetaltos-24h"),
      ev("activePainSignal", "review", "Reviews", "Reviews praise care but complain about phone wait times and unclear emergency info online.", 3),
      ev("economicCapacity", "directory", "Directory", "Hospital-grade equipment, emergency surcharges, two branches.", 2),
      ev("visibleTension", "web", "Audit", "New 24h service barely visible on the site; no clear emergency CTA.", 2),
      ev("whyNow", "press", "Press", "24h launch this quarter.", 2),
    ],
    tensions: ["growth_structure", "visibility_conversion", "expansion_systems"],
    thesis: "This company is likely losing emergency-visit revenue because it has not yet solved clear emergency information and contact pathways online for its new 24h service.",
    summary: "A vet hospital launched 24h emergency care and a second branch, but the new service is nearly invisible online with no clear emergency CTA. In emergencies pet owners search fast — and the site doesn't answer.",
    whyNow: "24h service launched this quarter; emergency discoverability is a revenue lever from day one.",
    whyBeforeOthers: "Strong active pain + clear lever; decision-maker reach via website/phone slightly softer than top leads.",
    blindSpot: "In a pet emergency, owners pick whoever answers clearly first — the site is losing that race.",
    firstLever: "Emergency-clear web + local SEO for '24h vet' queries.",
    offer: "web_funnel",
    callOpening: "Dr. Gil, lanzasteis urgencias 24h — pero en la web casi no se ve. Cuando alguien busca veterinario de urgencia a las 3am, ¿os encuentra?",
    objection: "Nos conocen en la zona.",
    objectionResponse: "La gente que ya os conoce, sí. La urgencia nueva que busca en Google a las 3am se va al primero que responde claro. Ahí está el ingreso que se escapa.",
    reasonsNotToCall: ["May rely on local word-of-mouth.", "Director time-poor running a hospital."],
    invalidators: ["Emergency info and SEO already handled.", "Second branch covers all demand."],
  }),

  mk({
    id: "g-fashion-noria",
    company: "Noria Atelier",
    sector: "growth",
    subsector: "Premium fashion / accessories brand",
    city: "Madrid",
    region: "Madrid",
    website: "https://noriaatelier.example.com",
    instagram: "@noria.atelier",
    linkedin: "company/noria-atelier",
    googleMaps: null,
    phone: null,
    email: "studio@noriaatelier.example.com",
    dm: { name: "Inés Vallejo", role: "Creative Director / Founder", linkedin: "in/ines-vallejo" },
    S: "GGGGYGGGGG",
    evidence: [
      ev("transitionSignal", "press", "Fashion press", "Featured in a national magazine and invited to a Paris showroom this season.", 3, "https://press.example/noria-paris"),
      ev("whyNow", "press", "Fashion press", "Paris showroom + press wave happening this season — international moment now.", 3),
      ev("visibleTension", "web", "Audit", "Editorial-level product on a basic Shopify theme; brand story underbuilt.", 3),
      ev("economicCapacity", "web", "Pricing", "Premium price points, growing wholesale interest.", 2),
      ev("strategicFit", "inference", "Analysis", "Visually rich brand = exceptional XN/01 case study.", 3),
      ev("reachableDecisionMaker", "instagram", "Instagram/LinkedIn", "Founder active and reachable on both.", 2),
    ],
    tensions: ["quality_perception", "ambition_maturity", "visibility_conversion"],
    thesis: "This company is likely underusing an international press moment because it has not yet solved a brand world and digital experience worthy of its product and the rooms it's now entering.",
    summary: "A premium fashion atelier is having an international moment — national press and a Paris showroom — on a basic Shopify theme with an underbuilt brand story. The window to match perception to product is open now and brief.",
    whyNow: "Press wave and Paris showroom are this season — international buyers and editors are looking now.",
    whyBeforeOthers: "Rare alignment of timing, capacity, tension, reachable founder and standout case-study value — a strong XN candidate.",
    blindSpot: "International press sends people to a site that undersells the brand — the moment converts far below its potential.",
    firstLever: "Brand world + elevated digital experience and editorial storytelling.",
    offer: "xn_transformation",
    callOpening: "Inés, vi lo de París y la prensa — felicidades. Ese momento manda gente a tu web. ¿Está a la altura de lo que verán en el showroom?",
    objection: "Estoy centrada en la colección y el showroom.",
    objectionResponse: "Justo por eso: el showroom genera el interés, pero la web es donde el comprador internacional decide. Que las dos cosas cuenten la misma historia.",
    reasonsNotToCall: ["Founder fully absorbed by the collection.", "Email-only contact may slow response."],
    invalidators: ["A brand studio already engaged for the press moment.", "The Shopify theme is a deliberate interim choice with a fix dated."],
  }),
];

export default SEED;
